# Generated by Django 3.1 on 2020-11-21 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20201115_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='numberOfCommittees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 7, 52, 39, 461642), verbose_name='date joined'),
        ),
    ]
